BLOB_IMAGE='blob'
BOUNDING_BOX='bounding_box'
PIXELS='pixels'
PERIMETER_IMAGE='perimeter_image'
CONVEX_HULL_IMAGE='convex_hull_image'
ROTATED_BLOB_IMAGE='rotated_blob_image'

AREA='area'
EQUIV_DIAMETER='equiv_diameter'
EXTENT='extent'
CONVEX_AREA='convex_area'
CONVEX_PERIMETER='convex_perimeter'
FERET_DIAMETER='feret_diameter'
MINOR_AXIS_LENGTH='minor_axis_length'
MAJOR_AXIS_LENGTH='major_axis_length'
ECCENTRICITY='eccentricity'
ORIENTATION='orientation'
PERIMETER='perimeter'
SOLIDITY='solidity'


