#!/bin/bash

SYSTEM_USER=ifcb
DATABASE_USER=ifcb
DATABASE_PASSWORD=ifcb

BASE_URL=http://localhost:5061/

. deps.sh
. user_db.sh
. config.sh

. add_time_series.sh mvco_test "/home/ifcb/data" "/home/ifcb/data/blobs" "/home/ifcb/data/features"
. add_time_series.sh saltpond_test "/home/ifcb/data2 /home/ifcb/data3" "/home/ifcb/data2/blobs" "/home/ifcb/data2/features"

. start.sh

