#!/bin/bash

SYSTEM_USER=ifcb
DATABASE_USER=ifcb
DATABASE_PASSWORD=ifcb

BASE_URL=http://localhost:5061/

. deps.sh
. user_db.sh
. config.sh

. add_time_series.sh mvco_test "/home/ifcb/data"

. start.sh

